config/routes.rb
Bluebanana::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :events do
    collection do
      get 'eventbrite'
    end
    member do
      resources :attendees
      post 'checkin'
      post 'meeting'
    end
  end
  resources :profiles

  root :to => 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :meetings
  has_many :checkins
  
  attr_accessible :eventbrite_id, :title, :description, :start, :end, :hashtag, :latitude, :longitude, :foursquare_venue_id
end

app/controllers/events_controller.rb
require 'event_brite'

class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :checkin, :meeting]

  def index
    @events = Event.all

    respond_to do |format|
      format.html
      format.json { render :json => @events }
    end
  end

  def new
    @event = Event.new
  end

  def create
    event = Event.new(params[:event])
    event.save!

    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event.update_attributes(params[:event])

    redirect_to events_path
  end

  def eventbrite
    raw_data = EventBrite.get("/event_get", :query => { :id => params[:id], :app_key => "4BVWLKSTKBR2VG2FSL"})
    data = Hash.new
    data["title"] = raw_data["event"]["title"]
    data["description"] = raw_data["event"]["description"]
    data["start"] = raw_data["event"]["start_date"]
    data["end"] = raw_data["event"]["end_date"]
    data["latitude"] = raw_data["event"]["venue"]["latitude"]
    data["longitude"] = raw_data["event"]["venue"]["longitude"]
    respond_to do |format|
      format.json { render :json => data }
    end
  end

  def checkin
    checkin = Checkin.new
    checkin.user = User.find(params[:user_id])
    checkin.event = Event.find(params[:id])
    checkin.save!

    respond_to do |format|
      format.json { render :json => { :checkin_id => checkin.id } }
    end
  end

  def meeting
    meeting = Meeting.new
    meeting.event = Event.find(params[:id])
    meeting.user = User.find(params[:user_id])
    if params[:acquaintance_id]
      meeting.acquaintance = User.find(params[:acquaintance_id])
    end
    meeting.acquaintance_first_name = params[:acquaintance_first_name]
    meeting.acquaintance_last_name = params[:acquaintance_last_name]
    meeting.acquaintance_source = params[:acquaintance_source]
    meeting.notes = params[:notes]
    meeting.save!

    respond_to do |format|
      format.json { render :json => { :meeting_id => meeting.id } }
    end
  end
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= f.label :eventbrite_id, "Eventbrite ID" %>
  <%= f.text_field :eventbrite_id %>

  <span id="spinner" style="display: none;">
    <%= image_tag "spinner.gif" %>
  </span>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :start %>
  <%= f.text_field :start %>

  <%= f.label :end %>
  <%= f.text_field :end %>

  <%= f.label :hashtag %>
  <%= f.text_field :hashtag %>

  <%= f.label :latitude %>
  <%= f.text_field :latitude %>

  <%= f.label :longitude %>
  <%= f.text_field :longitude %>

  <%= f.label :foursquare_venue_id %>
  <%= f.text_field :foursquare_venue_id %>

  <p>
    <%= f.submit :class => "btn btn-primary" %>
  </p>
<% end %>

app/views/events/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>Events</h1>

<table class="table">
  <% @events.each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <% if user_signed_in? %>
        <td><%= link_to "Edit", edit_event_path(event), :class => "btn" %></td>
      <% end %>
      <td><%= link_to "View", attendees_path(event), :class => "btn" %></td>
    </tr>
  <% end %>
</table>
<%= link_to "New Event", new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>